apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory_api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: inventory_api
    spec:
      containers:
      - name: inventory_api
        image: walissoncasonatto/instance-inventory-api:17
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: inventory_api_service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: inventory_api_ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /V1
        backend:
          serviceName: test
          servicePort: 80