apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-api
  template:
    metadata:
      labels:
        app: inventory-api
    spec:
      containers:
      - name: inventory-api
        image: walissoncasonatto/instance-inventory-api:20
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthx
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
          successThreshold: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: log-level
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-host
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-name
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-port
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-api-service
spec:
  selector:
    app: inventory-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: inventory-api-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: inventory-api-service
          servicePort: 80